# config/packages/vich_uploader.yaml
vich_uploader:
  db_driver: orm

  mappings:
    hotel:
      uri_prefix: /images/hotel
      upload_destination: '%kernel.project_dir%/public/images/hotel'
      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true